### ISSUE TITLE
How necessary is local-local infomax?

### ISSUE THREAD

**Issue by seann999** [mila-iqia/atari-representation-learning#66]
I understand that global-global infomax can lead to some salient features to be neglected.
I can see global-local infomax as a way to get around this, but additionally having local-local infomax feels redundant. Is the LL loss a necessity to get the method working or does it simply improve results?

**Comment by ankeshanand** [comment]
Hi @seann999! Good question, you are right that having both global-local and local-local is probably redundant. In our experiments, the games we were tuning hyper-parameters on showed improvements with both the losses included, but we found there were other games later on where having one was sufficient. 

We thought the local-local loss is quite useful for future work though, especially if you have spatial latents and that's why we decided to keep that in. We also have on ongoing work where we just use the local-local loss and that seems to work quite well. 

Let me know if you have any more questions!
